package com.slamzoom.android.effects.templates;

import com.google.common.collect.ImmutableList;
import com.slamzoom.android.effects.interpolation.filter.group.BulgeDoubleLeftRightFilterInterpolatorGroup;
import com.slamzoom.android.effects.interpolation.filter.group.BulgeEyesFilterInterpolatorGroup;
import com.slamzoom.android.effects.interpolation.filter.group.BulgeFaceFilterInterpolatorGroup;
import com.slamzoom.android.effects.interpolation.filter.group.BulgeLeftRightSwapFilterInterpolationGroup;
import com.slamzoom.android.effects.interpolation.filter.group.DeflateFaceFilterInterpolatorGroup;
import com.slamzoom.android.effects.interpolation.filter.group.InflateFaceFilterInterpolatorGroup;
import com.slamzoom.android.effects.interpolation.filter.group.SumoBulge2FilterInterpolator;
import com.slamzoom.android.effects.interpolation.filter.group.SumoBulgeFilterInterpolator;
import com.slamzoom.android.effects.interpolation.filter.single.BulgeInAtHotspotFilterInterpolator;
import com.slamzoom.android.effects.interpolation.filter.single.GaussianBlurFilterInterpolator;
import com.slamzoom.android.effects.interpolation.filter.single.GaussianUnblurFilterInterpolator;
import com.slamzoom.android.effects.interpolation.filter.single.GuassianSuperBlurFilterInterpolator;
import com.slamzoom.android.effects.interpolation.filter.single.ShrinkInAtHotspotFilterInterpolator;
import com.slamzoom.android.effects.interpolation.filter.single.UnsaturateFilterInterpolator;
import com.slamzoom.android.effects.interpolation.filter.single.ZoomBlurAtHotspotFilterInterpolator;
import com.slamzoom.android.effects.interpolation.transform.scaletranslate.CrashBounceBottomInterpolatorProvider;
import com.slamzoom.android.effects.interpolation.transform.scaletranslate.CrashMissInterpolatorProvider;
import com.slamzoom.android.effects.interpolation.transform.scaletranslate.CrashRumbleInterpolatorProvider;
import com.slamzoom.android.effects.interpolation.transform.scaletranslate.CrashTaranInterpolatorProvider;
import com.slamzoom.android.effects.interpolation.transform.scaletranslate.ShakeSwitchInterpolatorProvider;
import com.slamzoom.android.effects.interpolation.transform.translate.MegaShakeInterpolatorProvider;
import com.slamzoom.android.effects.interpolation.transform.translate.ShakeInterpolatorProvider;
import com.slamzoom.android.effects.interpolation.transform.translate.SuperShakeInterpolatorProvider;
import com.slamzoom.android.interpolators.LinearInterpolator;
import com.slamzoom.android.interpolators.custom.HalfInAndOutInterpolator;
import com.slamzoom.android.interpolators.custom.OutAndInInterpolator;
import com.slamzoom.android.interpolators.custom.OvershootInterpolator;
import com.slamzoom.android.interpolators.custom.SlamHardInterpolator;
import com.slamzoom.android.interpolators.custom.SlamHardNoPauseInterpolator;
import com.slamzoom.android.interpolators.custom.SlamSoftOutInterpolator;
import com.slamzoom.android.interpolators.spline.CubicSplineInterpolator;
import com.slamzoom.android.interpolators.spline.LinearSplineInterpolator;
import com.slamzoom.android.interpolators.spline.PointListBuilder;

/**
 * Created by clocksmith on 6/16/16.
 *
 * All effects. Keep alphabetized.
 */
public class EffectTemplates {
  public static ImmutableList<EffectTemplate> list() {
    return ImmutableList.<EffectTemplate>builder()
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("blurcrash")
            .withStartDurationEndSeconds(0.5f, 0.8f, 1)
            .withScaleInterpolator(new SlamHardInterpolator())
            .withFilterInterpolator(new GaussianUnblurFilterInterpolator())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("blurmagic")
            .withStartDurationEndSeconds(0, 2, 1)
            .withScaleInterpolator(LinearSplineInterpolator.newBuilder()
                .withPoint(0, 0)
                .withPoint(0.4999f, 0)
                .withPoint(0.5f, 1)
                .withPoint(1, 1)
                .build())
            .withFilterInterpolator(new GuassianSuperBlurFilterInterpolator(LinearSplineInterpolator.newBuilder()
                .withPoint(0, 0)
                .withPoint(0.5f, 1)
                .withPoint(1, 0)
                .build()))
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("blurslam")
            .withStartDurationEndSeconds(0, 2, 1)
            .withScaleInterpolator(new SlamHardInterpolator())
            .withFilterInterpolator(new GaussianUnblurFilterInterpolator())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("blurshake")
            .withStartDurationEndSeconds(0, 2, 1)
            .withScaleInterpolator(new LinearInterpolator())
            .withTranslateInterpolator(new ShakeInterpolatorProvider())
            .withFilterInterpolator(new GaussianUnblurFilterInterpolator())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("blursmith")
            .withStartDurationEndSeconds(0, 2, 1)
            .withScaleInterpolator(LinearSplineInterpolator.newBuilder()
                .withPoint(0, 0)
                .withPoint(0.4f, 0)
                .withPoint(0.6f, 1)
                .withPoint(1, 1)
                .build())
            .withFilterInterpolator(new GaussianBlurFilterInterpolator(LinearSplineInterpolator.newBuilder()
                .withPoint(0, 0)
                .withPoint(0.4f, 0)
                .withPoint(0.6f, 1)
                .withPoint(1, 1)
                .build()))
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("bulger")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new LinearInterpolator())
            .withFilterInterpolator(new BulgeInAtHotspotFilterInterpolator())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("bulgeswap")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new LinearInterpolator())
            .withFilterInterpolatorGroup(new BulgeLeftRightSwapFilterInterpolationGroup())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("crashblur")
            .withStartDurationEndSeconds(0.75f, 0.75f, 2)
            .withScaleAndTranslateInterpolatorProvider(new CrashTaranInterpolatorProvider())
            .withFilterInterpolator(new GaussianBlurFilterInterpolator(LinearSplineInterpolator.newBuilder()
                .withPoint(0, 0)
                .withPoint(0.3f, 1)
                .withPoint(0.6f, 1)
                .withPoint(0.9f, 0)
                .withPoint(1, 0)
                .build()))
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("crashin")
            .withStartDurationEndSeconds(0.5f, 1, 2)
            .withScaleAndTranslateInterpolatorProvider(new CrashBounceBottomInterpolatorProvider())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("crashmiss")
            .withStartDurationEndSeconds(0.75f, 0.75f, 2)
            .withScaleAndTranslateInterpolatorProvider(new CrashMissInterpolatorProvider())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("crashrumble")
            .withStartDurationEndSeconds(0.5f, 1.5f, 0)
            .withScaleAndTranslateInterpolatorProvider(new CrashRumbleInterpolatorProvider())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("deflate")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new LinearInterpolator())
            .withFilterInterpolatorGroup(new DeflateFaceFilterInterpolatorGroup())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("doublebulge")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new LinearInterpolator())
            .withFilterInterpolatorGroup(new BulgeDoubleLeftRightFilterInterpolatorGroup())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("earthquake")
            .withStartDurationEndSeconds(0, 2, 0)
            .withScaleInterpolator(new HalfInAndOutInterpolator())
            .withTranslateInterpolator(new SuperShakeInterpolatorProvider())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("grayfreeze")
            .withStartDurationEndSeconds(0.5f, 2, 2)
            .withScaleInterpolator(CubicSplineInterpolator.newBuilder()
                .withPoint(0, 0)
                .withPoint(0.15f, 1f)
                .withPoint(1f, 1f)
                .build())
            .withFilterInterpolator(new ZoomBlurAtHotspotFilterInterpolator(LinearSplineInterpolator.newBuilder()
                .withPoint(0, 0)
                .withPoint(0.7f, 0)
                .withPoint(0.9f, 1f)
                .withPoint(0.9999f, 1f)
                .withPoint(1f, 0)
                .build()))
            .withFilterInterpolator(new UnsaturateFilterInterpolator())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("grayrumble")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new LinearInterpolator())
            .withTranslateInterpolator(new ShakeInterpolatorProvider())
            .withFilterInterpolator(new UnsaturateFilterInterpolator())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("grayslam")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new SlamHardInterpolator())
            .withFilterInterpolator(new ZoomBlurAtHotspotFilterInterpolator(LinearSplineInterpolator.newBuilder()
                .withPoint(0, 0)
                .withPoint(0.7f, 0)
                .withPoint(0.9f, 1f)
                .withPoint(0.9999f, 1f)
                .withPoint(1f, 0)
                .build()))
            .withFilterInterpolator(new UnsaturateFilterInterpolator())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("grayson")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new LinearInterpolator())
            .withFilterInterpolator(new UnsaturateFilterInterpolator())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("graytake")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new OutAndInInterpolator())
            .withFilterInterpolator(new UnsaturateFilterInterpolator(new LinearInterpolator()))
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("inflate")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new LinearInterpolator())
            .withFilterInterpolatorGroup(new InflateFaceFilterInterpolatorGroup())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("magoo")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new LinearInterpolator())
            .withFilterInterpolatorGroup(new BulgeEyesFilterInterpolatorGroup())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("overcrash")
            .withStartDurationEndSeconds(0.5f, 1, 2)
            .withScaleInterpolator(new OvershootInterpolator())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("rumble")
            .withStartDurationEndSeconds(0, 2, 0)
            .withScaleInterpolator(new HalfInAndOutInterpolator())
            .withTranslateInterpolator(new ShakeInterpolatorProvider())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("rumbleslam")
            .withStartDurationEndSeconds(0, 2, 1)
            .withScaleInterpolator(new SlamHardInterpolator())
            .withTranslateInterpolator(new ShakeInterpolatorProvider())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("rumblestiltskin")
            .withStartDurationEndSeconds(0, 3, 0)
            .withScaleAndTranslateInterpolatorProvider(new ShakeSwitchInterpolatorProvider())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("shakezilla")
            .withStartDurationEndSeconds(0, 2, 0)
            .withScaleInterpolator(new HalfInAndOutInterpolator())
            .withTranslateInterpolator(new MegaShakeInterpolatorProvider())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("shrinkydink")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new LinearInterpolator())
            .withFilterInterpolator(new ShrinkInAtHotspotFilterInterpolator())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("slamin")
            .withStartDurationEndSeconds(1.4f, 0.6f, 2)
            .withScaleInterpolator(new SlamHardNoPauseInterpolator())
            .withFilterInterpolator(new ZoomBlurAtHotspotFilterInterpolator(LinearSplineInterpolator.newBuilder()
                .withPoint(0, 0)
                .withPoint(0.9f, 1)
                .withPoint(0.9999f, 1)
                .withPoint(1, 0)
                .build()))
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("slamout")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new SlamSoftOutInterpolator())
            .withFilterInterpolator(new ZoomBlurAtHotspotFilterInterpolator(LinearSplineInterpolator.newBuilder()
                .withPoint(0, 0)
                .withPoint(0.8f, 1)
                .withPoint(1, 0)
                .build()))
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("smush")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new LinearInterpolator())
            .withFilterInterpolatorGroup(new BulgeFaceFilterInterpolatorGroup())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("sumo")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new LinearInterpolator())
            .withFilterInterpolatorGroup(new SumoBulgeFilterInterpolator())
            .build())
        .add(EffectTemplate.newSingleStepBuilder()
            .withName("weirdo")
            .withStartDurationEndSeconds(0, 2, 2)
            .withScaleInterpolator(new LinearInterpolator())
            .withFilterInterpolatorGroup(new SumoBulge2FilterInterpolator())
            .build())
        .build();

  }
}
